<?php
/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */


require_once dirname(__DIR__) . '/vendor/autoload.php';
require_once dirname(__DIR__) . '/config/application.php';
require_once ABSPATH . 'wp-settings.php';
// define('JWT_AUTH_SECRET_KEY', 'u.wofws%Qk++V>kGiGM&D$`qV+m-APN(4(MKi(HA1+[u|i~?Y(}:xx}aDvi}5Ffz');
// define('JWT_AUTH_CORS_ENABLE', true);
